"""add_symbol_timeframe_to_strategy_fix_types

Revision ID: 1718a313bd6e
Revises: 847925f8963b
Create Date: 2026-05-27 23:19:00.988620
"""

import sqlalchemy as sa

from alembic import op

revision = "1718a313bd6e"
down_revision = "847925f8963b"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("strategies", sa.Column("symbol", sa.String(length=32), nullable=True))
    op.add_column("strategies", sa.Column("timeframe", sa.String(length=8), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("strategies", "timeframe")
    op.drop_column("strategies", "symbol")
    # ### end Alembic commands ###
